default_context:
  full_name: "Alexey Strokach"
  email: "alex.strokach@utoronto.ca"
  git_url: "https://gitlab.com"
  git_username: "ostrokach"
  anaconda_username: "ostrokach-forge"
  pypi_username: "ostrokach"
  project_name: "elaspic2-rest-api"
  project_slug: "elaspic2_rest_api"
  project_import: "elaspic2_rest_api"
  project_short_description: "ELASPIC v2 web server"
  version: "0.1.11"
  create_author_file: "y"
  open_source_license: "MIT License"
  _copy_without_render:
    - docs/output_toggle.tpl
    - docs/_templates/logo-image.html
    - docs/_templates/autosummary/class.rst
    - docs/_templates/autosummary/module.rst
    - .gitlab/pages/templates/index.html
