default:
  image: condaforge/linux-anvil-comp7:latest

stages:
  - test
  - deploy

variables:
  PACKAGE_VERSION: "0.1.2"
  PYTHON_VERSION: "3.8"

test:
  stage: test
  script:
    # Create clean environment
    - conda create -n test -q "python=${PYTHON_VERSION}"
    - source activate test

    # Lint
    - python -m pip install -q isort flake8 black mypy
    - python -m isort -p ${CI_PROJECT_NAME} -c .
    - python -m flake8 src
    - python -m black --config pyproject.toml --check .
    # MyPy does not support namespace packages until this issue gets resolved:
    # https://github.com/python/mypy/issues/1645
    - python -m mypy src/elaspic2_web || true

    # Test
    - python -m pip install -q -r requirements-base.txt -r requirements-dev.txt .
    - PKG_INSTALL_DIR=$(python -c "import elaspic2_web; print(elaspic2_web.__path__[0])")
    - python -m pytest
      -c setup.cfg
      --cov="${PKG_INSTALL_DIR}"
      --cov-config=setup.cfg
      --color=yes
      "tests/"

    # Coverage
    - coverage report
    - coverage html
  coverage: /^TOTAL.* (\d+\%)/
  artifacts:
    paths:
      - htmlcov

deploy:
  stage: deploy
  script:
    - echo "Deploying"
  only:
    - tags
