runtime: python38

instance_class: B2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
  # Matches requests to /images/... to files in static/images/...
  - url: /images
    static_dir: static/images
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

inbound_services:
  - warmup

basic_scaling:
  max_instances: 11
  idle_timeout: 10m

entrypoint: gunicorn src.ev2web.main:app -w 2 -k uvicorn.workers.UvicornWorker
