runtime: python38

instance_class: B2

includes:
  - env_variables.yaml

handlers:
  # Matches requests to /images/... to files in static/images/...
  - url: /images
    static_dir: static/images
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

inbound_services:
  - warmup

basic_scaling:
  max_instances: 11
  idle_timeout: 10m

entrypoint: gunicorn src.elaspic2_rest_api.main:app -w 2 -k uvicorn.workers.UvicornWorker
