dependencies:
  - python =3.8
  - aiofiles =0.6
  - aiohttp =3.7
  - aiomysql =0.0.21
  - bleach =3.3
  - fastapi =0.63
  - fire =0.4
  - gunicorn =20.0
  - jinja2 =2.11
  - python-dotenv =0.15
  - sentry-sdk =0.20
  - uvicorn =0.13
  - python-gitlab =2.6
