#!/bin/bash -l

# Copied from: https://github.com/conda-forge/docker-images/blob/master/scripts/entrypoint

# Use non-interactive cp
# unalias cp

# Create conda user with the same uid as the host, so the container can write
# to mounted volumes
# Adapted from https://denibertovic.com/posts/handling-permissions-with-docker-volumes/
USER_ID=${HOST_USER_ID:-9001}
GROUP_ID=${HOST_GROUP_ID:-9001}
groupadd -g ${GROUP_ID} elaspic
useradd --shell /bin/bash -u $USER_ID -g elaspic -G conda -o -c "" -m elaspic
export HOME=/home/elaspic
export USER=elaspic
export LOGNAME=elaspic
export MAIL=/var/spool/mail/elaspic
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/elaspic/bin
export supkg="su-exec"
chown elaspic:elaspic $HOME
cp -R /etc/skel $HOME && chown -R elaspic:elaspic $HOME/skel && (ls -A1 $HOME/skel | xargs -I {} mv -n $HOME/skel/{} $HOME) && rm -Rf $HOME/skel

# cp /root/.condarc $HOME/.condarc && chown conda:conda $HOME/.condarc
cd $HOME

# Add ssh key
mkdir -p $HOME/.ssh && chmod 700 $HOME/.ssh
echo "$KNOWN_HOSTS" >> $HOME/.ssh/known_hosts && chmod 644 $HOME/.ssh/known_hosts
echo "$SSH_PRIVATE_KEY" | tr -d '\r' | sed 's/\\n/\n/g' > $HOME/.ssh/id_ed25519 && chmod 600 $HOME/.ssh/id_ed25519
chown elaspic:elaspic -R $HOME/.ssh

# Activate the `base` conda environment.
source /opt/conda/etc/profile.d/conda.sh
conda activate app

# Copy script files (comment out so we don't break current installation when debugging)
/opt/conda/bin/$supkg elaspic python -m elaspic2_rest_api --log-level debug copy-scripts

# Run whatever the user wants
umask 002
exec /opt/conda/bin/$supkg elaspic "$@"
