{% set data = load_setup_py_data() %}

package:
  name: elaspic2-rest-api
  version: 0.1.3

source:
  path: ../../

build:
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  number: 0
  noarch: python

requirements:
  build:
    - python
  run:
    - python
    {% for req in data.get('install_requires', []) %}
      - {{ req }}
    {% endfor %}

    # Webserver packages
    - aiofiles =0.5
    - aiohttp =3.7
    - aiomysql =0.0.21
    - bleach =3.2
    - fastapi =0.61
    - fire =0.3
    - gunicorn =20.0
    - jinja2 =2.11
    - python-dotenv =0.15
    - sentry-sdk =0.19
    - uvicorn =0.11
    # Other packages
    - python-gitlab =2.5

test:
  imports:
    - elaspic2_rest_api

about:
  home: https://gitlab.com/elaspic/elaspic2-rest-api
  license: MIT License
  summary: "ELASPIC2 REST API"
