{% set data = load_setup_py_data() %}

package:
  name: elaspic2-rest-api
  version: 0.1.3

source:
  path: ../../

build:
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  number: 0
  noarch: python

requirements:
  build:
    - python
  run:
    - python
    {% for req in data.get('install_requires', []) %}
      - {{ req }}
    {% endfor %}

test:
  imports:
    - elaspic2_rest_api

about:
  home: https://gitlab.com/elaspic/elaspic2-rest-api
  license: MIT License
  summary: "ELASPIC2 REST API"
